package com.xwzx.equipmanager.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xwzx.equipmanager.mvp.models.LoginModel;

import com.xwzx.equipmanager.db.LoginModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginModelDaoConfig;

    private final LoginModelDao loginModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginModelDaoConfig = daoConfigMap.get(LoginModelDao.class).clone();
        loginModelDaoConfig.initIdentityScope(type);

        loginModelDao = new LoginModelDao(loginModelDaoConfig, this);

        registerDao(LoginModel.class, loginModelDao);
    }
    
    public void clear() {
        loginModelDaoConfig.clearIdentityScope();
    }

    public LoginModelDao getLoginModelDao() {
        return loginModelDao;
    }

}
